apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Homepage
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      - Services:
          style: row
          columns: 3
    
  services.yaml: |
    - Infrastructure:
        - Kubernetes:
            icon: kubernetes.png
            description: Cluster Kubernetes
            
  bookmarks.yaml: |
    - Administration:
        - ArgoCD:
            - icon: argocd.png
              href: http://192.168.0.240
        - Nginx:
            - icon: nginx.png
              href: http://nginx.junon.idarius.net
        - Homepage:
            - icon: homepage.png
              href: http://home.junon.idarius.net
              
  widgets.yaml: |
    - search:
        provider: google
        target: _blank