apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homepage
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      - Services:
          style: row
          columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Administration:
        - ArgoCD:
            - icon: argocd.png
              href: http://192.168.0.240
        - Nginx:
            - icon: nginx.png
              href: http://nginx.junon.idarius.net
        - Homepage:
            - icon: homepage.png
              href: http://home.junon.idarius.net
  services.yaml: |
    - Infrastructure:
        - Kubernetes:
            icon: kubernetes.png
            description: Cluster Kubernetes
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""