apiVersion: apps/v1
kind: Deployment
metadata: { name: homepage }
spec:
  replicas: 1
  selector: { matchLabels: { app: homepage } }
  template:
    metadata: { labels: { app: homepage } }
    spec:
      initContainers:
      - name: init-config
        image: busybox:latest
        command: ['sh', '-c', 'cp -r /tmp/config-template/* /app/config/']
        volumeMounts:
        - name: config-template
          mountPath: /tmp/config-template
        - name: config
          mountPath: /app/config
      containers:
      - name: homepage
        image: ghcr.io/benphelps/homepage:latest
        ports: [{ containerPort: 3000 }]
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config-template
        configMap:
          name: homepage-config
      - name: config
        emptyDir: {}
