apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-gateway
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "2" }
spec:
  project: default
  source:
    repoURL: "https://github.com/idarius/Homelab.git"
    targetRevision: main
    path: clusters/junon/platform/traefik-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated: { prune: true, selfHeal: true }
