apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: default
  destination: { server: https://kubernetes.default.svc, namespace: traefik }
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.1.2
    helm:
      values: |
        providers:
          kubernetesIngress: { enabled: false }
          kubernetesCRD: { enabled: true }
          kubernetesGateway:
            enabled: true
        ports:
          web:
            port: 80
            expose:
              default: true
          websecure:
            port: 443
            expose:
              default: true
        ingressRoute:
          dashboard:
            enabled: false
        additionalArguments: [ "--api.insecure=false" ]
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]
  ignoreDifferences:
  - group: gateway.networking.k8s.io
    kind: GatewayClass
    name: traefik
    jsonPointers:
    - /spec
    - /metadata
  - group: gateway.networking.k8s.io
    kind: Gateway
    jsonPointers:
    - /status
