apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage
  namespace: homepage-preprod
spec:
  parentRefs:
    - name: web
      namespace: traefik
  hostnames:
    - home-preprod.junon.idarius.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: homepage
      port: 80
